import logging
import os
import ssl
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Email, To, Content
from config.settings import get_settings

# Fix for macOS SSL Certificate Verify Failed error
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

logger = logging.getLogger(__name__)

class EmailService:
    def __init__(self) -> None:
        settings = get_settings()
        self.api_key = settings.sendgrid_api_key
        if not self.api_key:
            logger.warning("SendGrid API Key missing. Email functionality disabled.")

    def send_report(self, to_email: str, analysis: dict) -> bool:
        if not self.api_key:
            return False

        try:
            # Format the data for the email with null-safety
            summary = analysis.get("summary", "No summary provided.")
            risks = analysis.get("risks") or []
            strategy = analysis.get("strategy") or []

            risks_html = "".join([f"<li><b>{r['risk']}</b> ({r.get('severity', 'Note')}): {r.get('mitigation', '')}</li>" for r in risks])
            strategy_html = "".join([f"<li>{s['step']} - <i>{s.get('priority', 'Normal')}</i></li>" for s in strategy])
            
            html_content = f"""
            <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto;">
                <h1 style="color: #6366f1;">LexAI Legal Analysis Report</h1>
                <p>Here is your intelligent legal analysis for <b>{analysis.get("document_type", "Legal Document")}</b>.</p>
                
                <h2 style="border-bottom: 2px solid #6366f1;">Brief Summary</h2>
                <p style="background: #f8fafc; padding: 15px; border-radius: 8px;">{summary}</p>
                
                <h2 style="border-bottom: 2px solid #ef4444;">Legal Risks Identified</h2>
                <ul>{risks_html if risks_html else "<li>No specific risks flagged.</li>"}</ul>
                
                <h2 style="border-bottom: 2px solid #10b981;">Strategic Action Plan</h2>
                <ol>{strategy_html if strategy_html else "<li>No strategy steps generated.</li>"}</ol>
                
                <hr style="margin: 40px 0; border: 0; border-top: 1px solid #ddd;" />
                <p style="font-size: 12px; color: #999; text-align: center;">
                    Generated by LexAI Agentic Cloud Intelligence.
                </p>
            </div>
            """

            message = Mail(
                from_email='zhrizvi476@gmail.com',
                to_emails=to_email,
                subject=f"LexAI Analysis: {analysis.get('document_type', 'New Document')}",
                html_content=html_content
            )

            sg = SendGridAPIClient(self.api_key)
            response = sg.send(message)
            if response.status_code in [200, 201, 202]:
                logger.info("[EmailService] Report sent successfully to %s", to_email)
                return True
            else:
                logger.error("[EmailService] SendGrid Reject: %s | Response: %s", response.status_code, response.body)
                return False
        except Exception as e:
            logger.error("[EmailService] Critical Failure: %s", str(e))
            if hasattr(e, 'body'):
                logger.error("[EmailService] SendGrid Details: %s", e.body)
            return False
